### ISSUE TITLE
License & spices support

### ISSUE THREAD

**Issue by NikoKrause** [petrucci4prez/CinnXP#10]
You don't have a license added to your theme. Could you add it?

**Comment by ndwarshuis** [comment]
since you asked, any preference?

**Comment by NikoKrause** [comment]
Since you have done all the work, it's up to you.
Mint-Y (https://github.com/linuxmint/mint-y-theme) and Arc-Theme (https://github.com/horst3180/arc-theme) are using GPL-3.0

Have you used any base to create the theme (Adwaita?). If yes, I would look, which license they use. Probably also GPL.

I'm not an expert with this thing though.

**Comment by Elbullazul** [comment]
@NikoKrause all gnome work is lgpl licensed, of what I learned
