### ISSUE TITLE
Nemo sidebar looks weird

### ISSUE THREAD

**Issue by NikoKrause** [petrucci4prez/CinnXP#12]
Thanks for all your effort.

I found a little bug. The nemo sidebar looks weird:
![screenshot-area-2017-01-11-022533](https://cloud.githubusercontent.com/assets/8415124/21831631/788b6d38-d7a5-11e6-892b-004483b5ca5a.png)

I'm using Linux Mint 18.1 Cinnamon 3.2.7
I compiled your theme with gtk 3.18.

**Comment by Elbullazul** [comment]
@NikoKrause @petrucci4prez also to note, in Nautilus, sidebar is white:
![screenshot_2017-01-10_20-30-13](https://cloud.githubusercontent.com/assets/15310985/21831689/a1ecbb3c-d773-11e6-8cba-9b9f38155464.png)

maybe this is part of the issue?

**Comment by ndwarshuis** [comment]
@NikoKrause please add your nemo version as well as the exact compile flags you used to build

@Elbullazul this was never meant to work with anything outside the cinnamon DE

**Comment by NikoKrause** [comment]
Nemo version is 3.2.2

Linux Mint 18.1 uses GTK 3.18, so I changed a line in `compile-theme` to
```
gtk3_minor_revision=18
```
and compiled with the command `./compile-theme`

**Comment by Elbullazul** [comment]
@petrucci4prez yes, but the same class (something close to .sidebar) is used that causes the nemo bug, I guess.

note that royale doesn't have the bug on my system

**Comment by ndwarshuis** [comment]
.sidebar should be white. Nemo is the exception. In this case my compile script is actually wrong and assumes that gtk3.18 tracks with a lower Nemo version (3.0 or less)

**Comment by NikoKrause** [comment]
Is it something that I can change by myself, like changing the GTK version from 3.20 to 3.18. Or is this a bigger change?

**Comment by ndwarshuis** [comment]
won't be that simple. Gtk renamed all their selectors b/t 3.18 and 3.20, so salvaging 3.20 code will end up making your entire desktop unthemed. Essentially I have to decouple the nemo css from the rest of the gtk css.

This should be possible because I'm using Arch with Nemo 3.2.x and gtk3.22, but worst case scenario I'll need to make a separate nemo section for each nemo/gtk combination

**Comment by ndwarshuis** [comment]
nm, I just linked the wrong files. try it now

**Comment by NikoKrause** [comment]
Thank you very much! It works! And looks as always great :)
