### ISSUE TITLE
[Feature request] Smaller toolbar buttons

### ISSUE THREAD

**Issue by germanfr** [petrucci4prez/CinnXP#16]
Could you do this toolbar buttons smaller? Like they are too tall right now.

![screenshot from 2017-01-21 13-03-15](https://cloud.githubusercontent.com/assets/10391266/22174259/1b5cf52c-dfda-11e6-9eee-c0b523d73c7d.png)

Something like this would be nicer
![screenshot from 2017-01-21 13-07-13](https://cloud.githubusercontent.com/assets/10391266/22174273/9c5bcb76-dfda-11e6-8fff-f12c1eb4d70c.png)

**Comment by ndwarshuis** [comment]
huh, you're right. fixed in 3.10 and 3.20 (not sure if it's possible in 3.18, as all themes seem to have the same height)

**Comment by ndwarshuis** [comment]
nm, what version are you using? I'll keep open if you meant this for 3.18

**Comment by germanfr** [comment]
I'm not sure but I think I'm on 3.22.

**Comment by ndwarshuis** [comment]
so arch or some other bleeding edge distro, not LM18?

**Comment by germanfr** [comment]
Yeah Manjaro (Arch based). I didn't see you fixed it already. It looks fine now. Thanks!
