### ISSUE TITLE
Missing "Close" button in GeoGebra properties

### ISSUE THREAD

**Issue by NikoKrause** [petrucci4prez/CinnXP#17]
Hey,

when I open GeoGebra adding a dot, line or triangle, then right click on it and select "Properties",
the window, which opens, has no "Close" (red "X") button with CinnXP themes (I tried Luna, Royale and Metallic). (See the small window in the screenshot below)

![screenshot-window-2017-01-23-131912](https://cloud.githubusercontent.com/assets/8415124/22203883/6e80ba04-e16f-11e6-8484-dabf5d5a873a.png)

P.S.: Mint-X, Mint-Y and other themes have those button. But Adwaita and HighContrast don't either.

**Comment by ndwarshuis** [comment]
weird that nobody pointed this out earlier, as all the dialogs in XP have buttons on the titlebar. Metacity themes are undergoing some significant internal changes so this will get fixed then
