### ISSUE TITLE
Latest Git Version Compiles Luna as Metallic GTK

### ISSUE THREAD

**Issue by dominichayesferen** [petrucci4prez/CinnXP#18]
I've downloaded the latest version and compiled it with the following:
GTK = 18
F = Metallic

...but when I got to apply the theme, it had the Metallic Thumbnail, but it was actually Luna Blue for the GTK Theme...

**Comment by NikoKrause** [comment]
Which command exactly did you compiled with?

**Comment by dominichayesferen** [comment]
@NikoKrause `./compile-theme -f metallic` (after changing the compiling file from GTK 3.20 to GTK 3.18)

**Comment by dominichayesferen** [comment]
@NikoKrause @petrucci4prez Managed to work around it by deleting 'luna' and linking 'metallic' in a symlink called 'luna'

**Comment by NikoKrause** [comment]
I don't know if it's an error due to the newest changes made by petrucci, but you can set the gtk Version:
`./compile-theme -g 18 -f luna`

**Comment by dominichayesferen** [comment]
@NikoKrause Yeah, nevermind, like I said, got it working with that workaround for now...

**Comment by ndwarshuis** [comment]
not sure I understand, is there any issue here? everything seems fine for me

**Comment by dominichayesferen** [comment]
@petrucci4prez When I tried it before using a workaround, the GTK theme it built (instead of Metallic) was Luna despite me saying to it to compile Metallic...

**Comment by NikoKrause** [comment]
This can be closed. It compiles right for me on LM 18.1
