### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by MichaelTunnell** [petrucci4prez/CinnXP#19]
All GitHub repos should provide screenshots or preferably a demo. Theme projects should treat screenshots as a necessity, in this case before and after screenshots.

**Comment by cinnamoner** [comment]
> Theme projects should treat screenshots as a necessity

The guy makes sense.

**Comment by ndwarshuis** [comment]
@MichaelTunnell is this a standard written somewhere or your own opinion? (out of curiosity)

**Comment by MichaelTunnell** [comment]
It's my opinion but it's shared by thousands of other people.

Source: https://www.reddit.com/r/linux/comments/4bca77/visual_blindness_of_linux_programmers/

You'll see the highest rated comment is directly related to themes.

**Comment by cinnamoner** [comment]
@petrucci4prez No, there are no guidelines/standandards/rules/requirements in conjunction with the matter. So, obviously is completely up to you. But I think the same as Tunnell concerning the present issue.

**Comment by ndwarshuis** [comment]
compelling enough

**Comment by cinnamoner** [comment]
@petrucci4prez Thanks. It's so much better now. 👍
