### ISSUE TITLE
Terminal colors, Scrollbar, etc.

### ISSUE THREAD

**Issue by NikoKrause** [petrucci4prez/CinnXP#2]
I really like this theme. The only issues I get, are when I set CinnXP as Controls in the themes settings of Cinnamon. Everything else looks great.

My issues are:
I got dotted boxes. The Terminal has black as background color and black as text color, so you can't see anything if you write something into your terminal. Also I can't see the scrollbar, e.g. if I open a PDF file and want to scroll down the scrollbar is grey as is the background.

Maybe I'm compiling it wrong. You write the Requirements are:
Gtk 3.18
Pixmap and Adwaita gtk2 engines
Ruby Sass (for building css from source)

Which packages exactly do I need to install (in a newly installed Linux Mit 17.3 Cinnamon OS) before compiling your theme?

I habe installed:
sudo apt-get install ruby-full bundler libxml2-utils
sudo gem install sass

But how do I get GTK 3.18 to work?

Thanks for your work.

**Comment by ndwarshuis** [comment]
I use Arch for my daily driver so I usually develop for the latest packages first...which in this case is gtk 3.18, cinnamon 2.8, etc. Linux Mint 17.3 uses gtk 3.10 (from ubuntu trusty) so unless you want to force install something upstream this is the latest available version.

fortunately for you and everyone else who uses mint, I'm just finishing up a gtk3 analogue for this theme that is tuned for gtk 3.10, so you should be able to use it w/o intervention...should be done around this weekend

**Comment by NikoKrause** [comment]
That are great new. Thanks for your effort.

I have a pull request for you: 
There is a way to put the opened menu to the left border of the screen. 

You need to change two lines in the cinnamon.css file.

in .popup-menu-boxpointer change
    -arrow-border-radius: 24px;
    -boxpointer-gap: -1.5px;

(actually this problem was discussed and solved here: https://github.com/mintystark/starkmenu/pull/11)

**Comment by NikoKrause** [comment]
Hey,

can you help me with my menu? I think this has something to do with the cinnamon.css file in CinnXP.

I want to get rid of the gap on top of the menu. And I want the bottom panel to be higher.

Thanks

![bildschirmfoto vom 2016-01-10 02 42 15](https://cloud.githubusercontent.com/assets/8415124/12223070/86c42bd6-b7cd-11e5-95db-14539eea22cf.png)

**Comment by cinnamoner** [comment]
@petrucci4prez 
I'll adopt this theme if you manage to pull this off as well.

**Comment by NikoKrause** [comment]
@petrucci4prez: One more question, then I'm done. I changed the background color of nemos sidebar.
 Now this happens:

When the window is inactive, the background color of selected directory gets gray. I want it to stay blue.

![bildschirmfoto vom 2016-01-10 20 46 57](https://cloud.githubusercontent.com/assets/8415124/12223571/7ddeffec-b7db-11e5-9c76-b7a573e6fd4d.png)

**Comment by cinnamoner** [comment]
@NikoKrause 
Guess what, it just so happens that I'm in front of XP ("the real deal") as I'm typing. Just how much higher do you want that menu relative to the taskbar? Or I'm getting it wrong.

Note: watching XP but typing from Android just to avoid misinterpretation.

**Comment by cinnamoner** [comment]
@petrucci4prez 
It resembles XP so much that It freaks me out. They said they ended support. It just so seems to me that they've changed their mind.

**Comment by ndwarshuis** [comment]
which applet is this? it appears to be the starkmenu but when I pull the one from spices it looks like this:

![selection_052](https://cloud.githubusercontent.com/assets/6629118/12224052/8c7b29b6-b7b5-11e5-852b-98b3cc1da35b.png)

did either of you modify it in any way or update it to work with 2.8?

**Comment by NikoKrause** [comment]
Yes it is StarkMenu. This happenes also to me with the applet from spices. Here is a fixed Version: https://github.com/NikoKrause/starkmenu

**Comment by cinnamoner** [comment]
@NikoKrause 
Have you asked why does it turn gray right there, where the tiny little line/bar/whatever indicating occupied space on volume is? I bet it's no coincidence.

**Comment by cinnamoner** [comment]
@petrucci4prez 
It's already in its 2nd phase of update to 2.8. Just went from very good to nearly perfect.

**Comment by cinnamoner** [comment]
@NikoKrause 
I've been following you though the day and let me say that your qualities are undeniable. Very good communicator indeed. Not too little not too much, just enough to efficiently go wherever you wanna go. It's been a quality encounter. Thanks for everything and keep in touch. Cinnamoner out.

**Comment by NikoKrause** [comment]
@petrucci4prez: I solved the problem with the StarkMenu. But not that one with the sidebar in nemo. A little hint where to locate the problem would be great.

Here's the part of the cinnamon-applications.css file I changed in:

@define-color nemo_sidebar_bg #6d89dd;
@define-color nemo_sidebar_fg #fff;
@define-color nemo_sidebar_selected_fg #fff;

/********
- Nemo *
  ********/
  NemoTrashBar.info,
  NemoXContentBar.info,
  NemoQueryEditor.toolbar.primary-toolbar {
  background-color: @theme_bg_color;
  background-image: none;
  color: @theme_fg_color;
  text-shadow: none;
  border: none;
  box-shadow: inset 1px 1px alpha(white, 0.6),
              inset -1px -1px alpha(black, 0.2);
  }

NemoSearchBar.info {
  color: white;
  background-color: #d6dff7;
  border: 1px solid @borders_color;
  border-width: 0px 0px 1px 0px;
}

NemoWindow .sidebar .view {
    -GtkWidget-focus-padding: 0;
    -GtkWidget-focus-line-width: 1;
    -GtkTreeView-vertical-separator: 0;
    background-color: @nemo_sidebar_bg;
    color: @nemo_sidebar_fg;
    text-shadow: none;
    icon-shadow: none;
}

NemoWindow .sidebar .view:selected {
    border-color: @nemo_sidebar_bg;
    color: @nemo_sidebar_selected_fg;
    text-shadow: 1px 1px alpha(black, 0.2);
    icon-shadow: 1px 1px alpha(black, 0.2);
}

NemoWindow .sidebar .expander:selected {
    border-color: @nemo_sidebar_selected_fg;
    color: @nemo_sidebar_selected_fg;
}

**Comment by ndwarshuis** [comment]
@NikoKrause

just updated the package with the blue sidebar bg as cinnamoner has it above (looks more like XP than what I had)

for your curiosity, the selector for which you were looking is "NemoWindow .sidebar row" (with "hover," "selected," and "backdrop" performing their expected pseudo-selector functions)

**Comment by NikoKrause** [comment]
@petrucci4prez: Thanks it works great.
