### ISSUE TITLE
Compile Does not work

### ISSUE THREAD

**Issue by daemonspudguy** [petrucci4prez/CinnXP#20]
Compile does not actually compile properly.

**Comment by ndwarshuis** [comment]
More details plz? What flags? Error messages? Etc

**Comment by daemonspudguy** [comment]
I pass -g 18 it says the following code`ln: failed to create symbolic link '00008160000006810000408080010102': File exists
ln: failed to create symbolic link '028006030e0e7ebffc7f7070c0600140': File exists
ln: failed to create symbolic link '03b6e0fcb3499374a867c041f52298f0': File exists
ln: failed to create symbolic link '08e8e1c95fe2fc01f976f1e063a24ccd': File exists
ln: failed to create symbolic link '1081e37283d90000800003c07f3ef6bf': File exists
ln: failed to create symbolic link '14fef782d02440884392942c11205230': File exists
ln: failed to create symbolic link '2870a09082c103050810ffdffffe0204': File exists
ln: failed to create symbolic link '3085a0e285430894940527032f8b26df': File exists
ln: failed to create symbolic link '3ecb610c1bf2410f44200f48c40d3599': File exists
ln: failed to create symbolic link '4498f0e0c1937ffe01fd06f973665830': File exists
ln: failed to create symbolic link '5c6cd98b3f3ebcb1f9c7f1c204630408': File exists
ln: failed to create symbolic link '6407b0e94181790501fd1e167b474872': File exists
ln: failed to create symbolic link '640fb0e74195791501fd1ed57b41487f': File exists
ln: failed to create symbolic link '9081237383d90e509aa00f00170e968f': File exists
ln: failed to create symbolic link '9d800788f1b08800ae810202380a0822': File exists
ln: failed to create symbolic link 'arrow': File exists
ln: failed to create symbolic link 'bd_double_arrow': File exists
ln: failed to create symbolic link 'bottom_left_corner': File exists
ln: failed to create symbolic link 'bottom_right_corner': File exists
ln: failed to create symbolic link 'bottom_side': File exists
ln: failed to create symbolic link 'bottom_tee': File exists
ln: failed to create symbolic link 'c7088f0f3e6c8088236ef8e1e3e70000': File exists
ln: failed to create symbolic link 'cross': File exists
ln: failed to create symbolic link 'cross_reverse': File exists
ln: failed to create symbolic link 'd9ce0ab605698f320427677b458ad60b': File exists
ln: failed to create symbolic link 'diamond_cross': File exists
ln: failed to create symbolic link 'dnd-none': File exists
ln: failed to create symbolic link 'dotbox': File exists
ln: failed to create symbolic link 'dot_box_mask': File exists
ln: failed to create symbolic link 'double_arrow': File exists
ln: failed to create symbolic link 'draft_large': File exists
ln: failed to create symbolic link 'draft_small': File exists
ln: failed to create symbolic link 'draped_box': File exists
ln: failed to create symbolic link 'e29285e634086352946a0e7090d73106': File exists
ln: failed to create symbolic link 'fcf1c3c7cd4491d801f1e1c78f100000': File exists
ln: failed to create symbolic link 'fd_double_arrow': File exists
ln: failed to create symbolic link 'fleur': File exists
ln: failed to create symbolic link 'grab': File exists
ln: failed to create symbolic link 'grabbing': File exists
ln: failed to create symbolic link 'hand1': File exists
ln: failed to create symbolic link 'hand2': File exists
ln: failed to create symbolic link 'h_double_arrow': File exists
ln: failed to create symbolic link 'icon': File exists
ln: failed to create symbolic link 'left_side': File exists
ln: failed to create symbolic link 'left_tee': File exists
ln: failed to create symbolic link 'll_angle': File exists
ln: failed to create symbolic link 'lr_angle': File exists
ln: failed to create symbolic link 'pirate': File exists
ln: failed to create symbolic link 'question_arrow': File exists
ln: failed to create symbolic link 'right_side': File exists
ln: failed to create symbolic link 'right_tee': File exists
ln: failed to create symbolic link 'tcross': File exists
ln: failed to create symbolic link 'top_left_arrow': File exists
ln: failed to create symbolic link 'top_side': File exists
ln: failed to create symbolic link 'top_tee': File exists
ln: failed to create symbolic link 'ul_angle': File exists
ln: failed to create symbolic link 'ur_angle': File exists
ln: failed to create symbolic link 'v_double_arrow': File exists
ln: failed to create symbolic link 'watch': File exists
ln: failed to create symbolic link 'X_cursor': File exists
ln: failed to create symbolic link 'xterm': File exists
Building flavor: luna (gtk3.18)
 - now building gtk3 theme
	
cp: cannot stat '/home/jacob/CinnXP/theme-src/luna/gtk-3.18/Check-Radio/selected_mask.png': No such file or directory
cp: cannot stat '/home/jacob/CinnXP/theme-src/luna/gtk-3.18/Progressbar/progressbar.png': No such file or directory
 - now building cinnamon theme
	
cp: cannot stat '/home/jacob/CinnXP/theme-src/luna/cinnamon/Buttons/button-hover.png': No such file or directory
cp: cannot stat '/home/jacob/CinnXP/theme-src/luna/cinnamon/Buttons/button-insensitive.png': No such file or directory
cp: cannot stat '/home/jacob/CinnXP/theme-src/luna/cinnamon/Buttons/button-pressed.png': No such file or directory
cp: cannot stat '/home/jacob/CinnXP/theme-src/luna/cinnamon/Buttons/button.png': No such file or directory
 - now copying gtk2 and metacity themes

`

**Comment by ndwarshuis** [comment]
What distro and ruby version?

**Comment by daemonspudguy** [comment]
Linux MInt 18 and 2.3.0

**Comment by ndwarshuis** [comment]
What files are in your tmp dir? It looks like the script crapped out in the middle the build files should still be in tmp

**Comment by daemonspudguy** [comment]
Okay. nothing involving CinnXP

**Comment by daemonspudguy** [comment]
![image](https://cloud.githubusercontent.com/assets/24438557/23528778/0ed4946e-ff69-11e6-961f-007a371cdfe0.png)

**Comment by NikoKrause** [comment]
Delete the pkg directory and post the output of compilation

**Comment by ndwarshuis** [comment]
^this

**Comment by NikoKrause** [comment]
Okay, I tried to compile and it looks that some symbolic links are broken.
I used `find . -xtype l` in the terminal and it shows the following broken symbolic links:

```
./theme-src/metallic/gtk-3.10/Progressbar/progressbar.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-checkbox-mixed.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-radio-mixed-hover.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-checkbox-mixed-insensitive.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-checkbox-unchecked.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-radio-checked-insensitive.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-radio-checked-hover.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-radio-unchecked-insensitive.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-radio-mixed-insensitive.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-checkbox-unchecked-hover.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-radio-mixed-active.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-checkbox-unchecked-active.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-radio-checked-active.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-checkbox-checked-hover.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-checkbox-mixed-hover.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-checkbox-checked.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-checkbox-mixed-active.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-radio-unchecked.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-radio-mixed.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-checkbox-checked-insensitive.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-radio-checked.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-checkbox-unchecked-insensitive.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-radio-unchecked-hover.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-radio-unchecked-active.png
./theme-src/metallic/gtk-3.10/Check-Radio/selected-checkbox-checked-active.png
./theme-src/metallic/gtk-3.20/Progressbar/progressbar.png
./theme-src/metallic/cinnamon/Buttons/button.png
./theme-src/metallic/cinnamon/Buttons/button-insensitive.png
./theme-src/metallic/cinnamon/Buttons/button-pressed.png
./theme-src/metallic/cinnamon/Buttons/button-hover.png
./theme-src/metallic/gtk-3.18/Check-Radio/selected_mask.png
./theme-src/luna/gtk-3.10/Progressbar/progressbar.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-checkbox-mixed.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-radio-mixed-hover.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-checkbox-mixed-insensitive.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-checkbox-unchecked.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-radio-checked-insensitive.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-radio-checked-hover.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-radio-unchecked-insensitive.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-radio-mixed-insensitive.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-checkbox-unchecked-hover.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-radio-mixed-active.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-checkbox-unchecked-active.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-radio-checked-active.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-checkbox-checked-hover.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-checkbox-mixed-hover.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-checkbox-checked.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-checkbox-mixed-active.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-radio-unchecked.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-radio-mixed.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-checkbox-checked-insensitive.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-radio-checked.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-checkbox-unchecked-insensitive.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-radio-unchecked-hover.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-radio-unchecked-active.png
./theme-src/luna/gtk-3.10/Check-Radio/selected-checkbox-checked-active.png
./theme-src/luna/gtk-3.20/Progressbar/progressbar.png
./theme-src/luna/cinnamon/Buttons/button.png
./theme-src/luna/cinnamon/Buttons/button-insensitive.png
./theme-src/luna/cinnamon/Buttons/button-pressed.png
./theme-src/luna/cinnamon/Buttons/button-hover.png
./theme-src/luna/gtk-3.18/Check-Radio/selected_mask.png
./theme-src/royale/gtk-3.10/Progressbar/progressbar.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-checkbox-mixed.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-radio-mixed-hover.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-checkbox-mixed-insensitive.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-checkbox-unchecked.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-radio-checked-insensitive.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-radio-checked-hover.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-radio-unchecked-insensitive.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-radio-mixed-insensitive.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-checkbox-unchecked-hover.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-radio-mixed-active.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-checkbox-unchecked-active.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-radio-checked-active.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-checkbox-checked-hover.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-checkbox-mixed-hover.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-checkbox-checked.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-checkbox-mixed-active.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-radio-unchecked.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-radio-mixed.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-checkbox-checked-insensitive.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-radio-checked.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-checkbox-unchecked-insensitive.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-radio-unchecked-hover.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-radio-unchecked-active.png
./theme-src/royale/gtk-3.10/Check-Radio/selected-checkbox-checked-active.png
./theme-src/royale/gtk-3.20/Progressbar/progressbar.png
./theme-src/royale/cinnamon/Buttons/button.png
./theme-src/royale/cinnamon/Buttons/button-insensitive.png
./theme-src/royale/cinnamon/Buttons/button-pressed.png
./theme-src/royale/cinnamon/Buttons/button-hover.png
./theme-src/royale/gtk-3.18/Check-Radio/selected_mask.png
```

**Comment by daemonspudguy** [comment]
@petrucci4prez @NikoKrause When will this be fixed?

**Comment by ndwarshuis** [comment]
try now

**Comment by daemonspudguy** [comment]
yay

**Comment by ndwarshuis** [comment]
@jacobpoo does this mean it works for you? if so plz close issue

**Comment by daemonspudguy** [comment]
@petrucci4prez Yes, I will now close

**Comment by NikoKrause** [comment]
Compiles for 3.10 as well. Thanks.
