### ISSUE TITLE
"Menu" font changed

### ISSUE THREAD

**Issue by NikoKrause** [petrucci4prez/CinnXP#21]
I don't know if this is a bug or on purpose.
The font of the Menu button changed.
Before it looked like this:
![screenshot-cinnamon-2017-03-05-230806](https://cloud.githubusercontent.com/assets/8415124/23591940/45d86a3e-01f9-11e7-9b43-1d70d626efed.png)

And now it looks like this:
![screenshot-cinnamon-2017-03-05-230544](https://cloud.githubusercontent.com/assets/8415124/23591944/4f180ee2-01f9-11e7-98f5-0b6acf3bbe85.png)

This is on Linux Mint 17.3 (Cinnamon 2.8.8). I compiled with `./compile-theme -g 10 -a`

**Comment by ndwarshuis** [comment]
this was deliberate. see commit 3f1ef52. start button now calls for Franklin Gothic Medium
