### ISSUE TITLE
Window border cannot be hiden when maximized

### ISSUE THREAD

**Issue by llpub** [petrucci4prez/CinnXP#22]
For gtk3 apps, if more than one tab are opened, the window border (exactly, here should be tab border) cannot be hiden when maximized.
E.g. xfce4-terminal 0.8.3 (based on gtk3) on debian 9 (installed gtk3.22);
If only one tab is opened, that border is not present when maximized.
This bug does not appear under system default Adwaita theme.
**UPDATE: This is solved** by editing 'theme-src/common/gtk-3.20/_common.scss', change 'border: 1px solid $notebook_borders;' --> 'border: 0px solid $notebook_borders;'
Thanks for this great theme.
multi tab mode:
![2tab_maximized_bug](https://cloud.githubusercontent.com/assets/25077000/24757805/da264738-1b12-11e7-9c6a-d10252a384a1.png)
one tab mode:
![1tab_maximized_ok](https://cloud.githubusercontent.com/assets/25077000/24757809/df7241c4-1b12-11e7-90d2-fab2c2977cf7.png)

**Comment by ndwarshuis** [comment]
I was able to fix this in gnome terminal (https://github.com/petrucci4prez/CinnXP/commit/47c35e5ec2742657ad738ca90d32a53a64a44688). Probably not possible to fix in xfce4 as there is no way to differentiate b/t the notebook stack in xfce4-terminal and everything else (unlike gnome terminal, which provides a unique selector)

are there any other apps this affects? It should only be noticeable when the notebook goes right to the edge of the window and has dark contents (which should only be terminal emulators?)

**Comment by llpub** [comment]
This can also be oberved in terminator 1.90 (gtk3). Not found in other apps by now.
For terminator, there is another problem, tab edge is missing.
**UPDATE:** This does not present in lastest terminator 1.91. 
![terminator1](https://cloud.githubusercontent.com/assets/25077000/24829681/0fdc8f8a-1ca9-11e7-9e17-a33ae57b8ab7.png)

**Comment by ndwarshuis** [comment]
which system is this? Arch has v1.91 and LM18.1 has v0.98...neither have this problem

**Comment by llpub** [comment]
This is a debian 9 (currently testing) system, desktop is xfce4 (4.12), gtk3 version is 3.22.
Maybe this is something related to debian testing? I will re-check this when debian 9 becames stable.

**Comment by ndwarshuis** [comment]
Terminator borders issue fixed (https://github.com/petrucci4prez/CinnXP/commit/1017d4c9650c4fc92144eba8c3f4b23c4d1e6c83).

The transparent header bg is a known [bug](https://code.launchpad.net/~laney/terminator/gtk3.20-embedded-css/+merge/316094) (they didn't update their selectors for gtk3.20 and newer apparently)
