### ISSUE TITLE
revert hard coded start button and icon

### ISSUE THREAD

**Issue by NikoKrause** [petrucci4prez/CinnXP#24]
In your last commit you hard coded the start button and icon (https://github.com/petrucci4prez/CinnXP/commit/412cd60a6373f30e1ec272032399074bc778d6bd)

If you don't use English but another language, you don't have a chance to change the text.
E.g. German has "Start" wit an uppercase first letter.
Spanish:
![Inicio](https://i0.fiuxy.com/52de6ae07e1514657be32931d0d3c7a35a61b047?url=http%3A%2F%2Fi266.photobucket.com%2Falbums%2Fii265%2FJ0gat0re%2FSinttulo-2.jpg)

Also the user has no chance to change the icon, if he wants to use another one.

So why this idea seems to be good, when you use English, it makes it harder for non-English speaker to use.

**Comment by ndwarshuis** [comment]
derp :/ I knew there was a reason I never did this until now...
