### ISSUE TITLE
Git master won't compile

### ISSUE THREAD

**Issue by Elbullazul** [petrucci4prez/CinnXP#29]
When running compile-theme:

```shell

elbullazul@localhost ~/Github/CinnXP $ ./compile-theme -f luna
Building cursor theme
	
./compile-theme: ligne 78: xcursorgen : commande introuvable
elbullazul@localhost ~/Github/CinnXP $ ./compile-theme -a
Building cursor theme
	
./compile-theme: ligne 78: xcursorgen : commande introuvable
elbullazul@localhost ~/Github/CinnXP $ ./compile-theme -a
Building cursor theme
	
Building flavor: luna (gtk3.20)
 - now building gtk3 theme
	
./parse-sass.sh: ligne 3: bundle : commande introuvable
elbullazul@localhost ~/Github/CinnXP $ 


```

**Comment by daemonspudguy** [comment]
@Elbullazul I don't get that, but people's systems are different. Mine, for example is a modded Linux Mint.

**Comment by ndwarshuis** [comment]
@Elbullazul you installed ruby bundler and xcursorgen?

**Comment by Elbullazul** [comment]
@petrucci4prez dumb me, I didn't check dependencies

**Comment by Elbullazul** [comment]
@petrucci4prez have the same thing happening, is it because you moved to SASS?

**Comment by ndwarshuis** [comment]
@Elbullazul check the README on the front page. I ditched ruby-sass in favor of sassc (adwaita did the same thing). Way simpler than dealing with multiple ruby versions across different mint versions, bleeding edge distros, etc (and it is orders of magnitude faster)
