### ISSUE TITLE
Luna flavor GTK3.18 broken buttons/controll

### ISSUE THREAD

**Issue by NikoKrause** [petrucci4prez/CinnXP#33]
Only Luna is broken. Other flavors are ok. See screenshot:

![screenshot-area-2017-07-03-215024](https://user-images.githubusercontent.com/8415124/27806273-daecc66c-6039-11e7-86a5-c094521189b0.png)

**Comment by ndwarshuis** [comment]
Can't reproduce. I now use sassc instead of ruby-sass for compilation; did you install this?

**Comment by NikoKrause** [comment]
Yes. I have sassc installed. All other flavors worked great.
I recompiled and can't reproduce it anymore.

Thanks for resolving menu applet issues that fast.
