### ISSUE TITLE
Cinnamon 3.2.0 breaking changes

### ISSUE THREAD

**Issue by dobragab** [petrucci4prez/CinnXP#8]
Cinnamon 3.2.0 contains breaking changes, this makes CinnXP look awful. See [this thread](https://github.com/linuxmint/Cinnamon/issues/5921) for further information.

**Comment by ndwarshuis** [comment]
yup, 3.2.x is not yet stable. fixes are small/easy but a there are a few bugs that need to be resolved on their end before cinnxp will look right

**Comment by dominichayesferen** [comment]
Cinnamon 3.2.2 has fixed the issue, try updating and seeing if it works now

> [ Stephen Collins ]
> Restore ability to theme the menu applet menu separately from other menus
> 
> Read more: http://news.softpedia.com/news/cinnamon-3-2-2-desktop-out-now-with-workspace-switcher-and-sound-applet-fixes-510459.shtml#ixzz4Qwny0voS

**Comment by ndwarshuis** [comment]
still waiting on Arch pkg maintainers

**Comment by dominichayesferen** [comment]
@petrucci4prez CinnXP on 3.2.2:
![screenshot from 2016-12-04 20-08-42](https://cloud.githubusercontent.com/assets/11057934/20868833/7f0e08ba-ba5d-11e6-94bf-db16e86cb3fc.png)
![screenshot from 2016-12-04 20-08-52](https://cloud.githubusercontent.com/assets/11057934/20868834/7f0eb65c-ba5d-11e6-9352-1636f4730c74.png)

**Comment by dominichayesferen** [comment]
...Also, your theme doesn't yet support Vertical Panels:
![screenshot from 2016-12-05 16-48-28](https://cloud.githubusercontent.com/assets/11057934/20893721/abc457ee-bb0a-11e6-8830-8b9d76d720f5.png)

**Comment by Elbullazul** [comment]
@feren I think that support for that feature on this theme is completely useless. I mean, you wouldn't use an XP theme if you didn't want it to look like XP...

**Comment by dominichayesferen** [comment]
@Elbullazul Meh, there was always the feature in Windows XP to have it on the right, it just made the taskbar really long from left-to-right...

**Comment by NikoKrause** [comment]
@feren 
Chill out. petrucci4prez hasn't updated his theme for 3.2 yet.

**Comment by Elbullazul** [comment]
@NikoKrause I doubt almost anyone apart from the mint devs has :/

**Comment by dominichayesferen** [comment]
@NikoKrause @Elbullazul I Know Right?

**Comment by ndwarshuis** [comment]
...and just so you guys aren't in the dark, the real reason I haven't updated to 3.2 is because Arch hasn't pushed the latest version yet (the one that alledgedly corrects the menu issue) Besides that I'll be busy up until Xmas...after I'll have more time

**Comment by dominichayesferen** [comment]
How to fix the menus in 3.2.2:
https://github.com/linuxmint/Cinnamon/issues/6056#issuecomment-264940228

**Comment by NikoKrause** [comment]
@petrucci4prez
I don't know, if this is interesting for CinnXP Themen, but there is a new pseudoclass called "checked".
It's for highlighting the open applet. The GIF here shows, what it does: https://github.com/linuxmint/Cinnamon/pull/5951

https://cloud.githubusercontent.com/assets/3822556/20245902/eba12f64-a989-11e6-95c3-6b37104b3d22.gif

**Comment by dominichayesferen** [comment]
@NikoKrause It won't affect CinnXP that much as it looks the same as unfocused in XP

**Comment by ndwarshuis** [comment]
Updated for 3.2. No plans to add support for vertical panels as XP never really had them (well, it did but they looked like crap, and trying to emulate that would look even worse in cinnamon)
