### ISSUE TITLE
CinnXP Metallic?

### ISSUE THREAD

**Issue by dominichayesferen** [petrucci4prez/CinnXP#9]
Well, I'm wondering, since both variants you've done look really good, would you mind making a CinnXP Silver theme? Silver was my favourite theme of the Luna trio and for good reason too, and I really miss it nowadays, it would require a bit more coding on the Cinnamon part (white text on active window, but black for inactive windows on Window List for example...) which I could help you with, please, I really want Silver so bad!

Also, could you try doing what Elbullazul is doing with the headerbars in all the variants you're doing? I'll drop a screenshot to show you what I mean:
![screenshot from 2016-11-25 14-02-08](https://cloud.githubusercontent.com/assets/11057934/20627422/c4d56f7a-b317-11e6-91ae-308fc4ca9bfa.png)

(I think that looks better after-changing than the current CinnXP headerbars)

**Comment by dominichayesferen** [comment]
Also, for your to-do list, in case you're curious:
Full Icon Theme - Elbullazul fixed YlmfOS to make it usable again properly, https://github.com/Elbullazul/WinXP-Icons
Zune, Embedded and Royale Noir - Elbullazul beat you to it: https://github.com/Elbullazul/Redmond-Themes (there's still room for improvement in Zune definitely)
Classic - Elbullazul (kinda) made one, but it's more of a Windows 95 theme to be honest...

**Comment by Elbullazul** [comment]
@feren not to rush you, but here's @petrucci4prez 's opinion on headerbars: https://github.com/petrucci4prez/CinnXP/issues/7

**Comment by dominichayesferen** [comment]
Ok, saw that

**Comment by ndwarshuis** [comment]
totes forgot about silver, shouldn't be too hard (basically luna w/ different images and colors)

**Comment by NikoKrause** [comment]
@petrucci4prez 
The bar in Metallic seems to use colors of luna:
![screenshot-area-2017-01-17-150308](https://cloud.githubusercontent.com/assets/8415124/22023393/468229fa-dcc6-11e6-9608-33cbda9ca038.png)

**Comment by ndwarshuis** [comment]
Which gtk version?

**Comment by NikoKrause** [comment]
It's 3.18
`./compile -g 18 -f metallic`

**Comment by ndwarshuis** [comment]
should be fixed now. also, please open new issue in the future so I can properly close it

**Comment by dominichayesferen** [comment]
@petrucci4prez Thanks... :3

**Comment by NikoKrause** [comment]
@petrucci4prez 
Thanks. The Metallic looks great now.
Next time I'll open a new issue, no problem.
